version: '3.8'

volumes:
  logs:
    driver: local

services:
  php: 
  build: 
  context: .
  dockerfile: ultralims-backend/api/dockerfile
  ports:
  - 80:80 
  volumes:
  - ./var/www/html

  mysqldatabase:
  container_name: mysql
  image: mysql
  restart: always
  environment:
  MYSQL_DATABESE: 
  MYSQL_ROOT_PASSWORD:
  MYSQL_USER: treinamentos_dev

  networks:

bridge: 

#app-front
#- ./ultralims-frontend:/app 
#- /app/node_modules 
#app-backend
# - .:/var/www/html 

#mysql
#  - ./mysql:/var/lib/mysql 
#  - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql 

#networks




 