version: '3.8'

volumes:
  logs:
    driver: local

services:
  backend:
    build: 
      context: ultralims-backend/api
      dockerfile: dockerfile
    container_name: ultralims_backend
    ports:
      - "8080:80"
    volumes:
      - backend: 



#app-front
#- ./ultralims-frontend:/app 
#- /app/node_modules 
#app-backend
# - .:/var/www/html 

#mysql
#  - ./mysql:/var/lib/mysql 
#  - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql 

#networks




 