version: '3.8'

volumes:
  mysql-volume:
    driver: local
  logs:
    driver: local

services:

#app-front
#- ./ultralims-frontend:/app 
#- /app/node_modules 
#app-backend
# - .:/var/www/html 

  db:
    image: mysql
    
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql 

    networks:
      - app-networks

#networks
networks:
  app-networks:
    driver: bridge 