version: '3.8'

services:
  db:
    image: mysql
    container_name: banco-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mysql-database
      - MYSQL_ROOT_PASSWORD=
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-networks

volumes:
  mysql-volume:
    driver: local
  logs:
    driver: local

networks:
  app-networks:
    driver: bridge
