version: '3.8'

volumes:
  mysql-volume:
    driver: local
  logs:
    driver: local

services:
  app-backend:
    build: 
      context: ./ultralims-backend/api/
      dockerfile: dockerfile
    container_name: ultralims_backend
    volumes:
      - ./ultralims-backend/api:/var/www/html
    ports:
      - "8080:80"
    networks:
      - ultralims-network

  app-front:
    networks:
      - ultralims-network
    build:
      context: ./ultralims-frontend
      dockerfile: dockerfile
    volumes:
      - ./ultralims-frontend:/app 
      - /app/node_modules 
    ports: 
      - "80:5173"

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - ultralims-network

networks:
  ultralims-network:
    driver: bridge
      



 
