version: '3.8'

volumes:
  logs:
    driver: local

services:
  app-front:
    networks:
      - frontend
    build:
      context: ./ultralims-frontend
      dockerfile: Dockerfile
    volumes:
      - ./ultralims-frontend:/app 
      - /app/node_modules 
    ports: 
      - "80:5173"

#app-backend
# - .:/var/www/html 

#mysql
#  - ./mysql:/var/lib/mysql 
#  - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql 

networks:
  frontend:
    driver: bridge




 